# @package _global_
seed: 42
num_epochs: 100
batch_size: 32
metrics: ["MAE", "MSE", "RMSE", "MAPE", "WAPE"]
optimizer_params:
  lr: 5.0e-4
  weight_decay: 0.01
lr_scheduler: torch.optim.lr_scheduler.CosineAnnealingLR
lr_scheduler_params:
  T_max: 100