# @package _global_
defaults:
  - /_base_/base
  - /_base_/datasets/ettm1
  - /_base_/model/mats_base
  - _self_

experiment:
  name: "ABL-NoCausal-ETTm1-96"
  type: ablation
  ablation_type: no_causal

output_len: 96
input_len: 96

model_params:
  use_temporal_causal: false
