# @package _global_
model: src.basicts_adapter.mats_arch.MATSArch
model_params:
  hidden_dim: 256
  use_segment_processing: false
  use_verification: true
  use_rft: false
  use_revin: true
  channel_independent: false
  input_dim: 7
  output_dim: 7
