# @package _global_
defaults:
  - /_base_/base
  - /_base_/datasets/pems04
  - /_base_/model/mats_base
  - _self_

experiment:
  name: "MATS-Full-PEMS04-96"
  type: main

output_len: 96
input_len: 96
